// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh9FV6rvMAVsMsVFi806e1opd9EPIfGGE',
    appId: '1:368004415090:web:eaa8ac5771f2125432cceb',
    messagingSenderId: '368004415090',
    projectId: 'visign-gallery',
    authDomain: 'visign-gallery.firebaseapp.com',
    storageBucket: 'visign-gallery.appspot.com',
    measurementId: 'G-V00KLMD5CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3b2ptD40NwUaD_6CpFmSXH_uYqNsZlXg',
    appId: '1:368004415090:android:24a84096b97c0e9232cceb',
    messagingSenderId: '368004415090',
    projectId: 'visign-gallery',
    storageBucket: 'visign-gallery.appspot.com',
  );
}
